globalConfig:
  enableBase: true
  enablePlatform: true
  esdeHome: 'D:\ES-DE'
  raHome: 'D:\ES-DE\Emulators\RetroArch-Win64'
  resHome: 'D:\resources'
  repo: 'https://github.com/deathbit/retroboy'
  author:
    name: '村长不可爱'
    wechat: '村长|paprika225'
    qq: '村长不可爱|809730879'
    tiktok: '村长不可爱|paprika0225'
    xhs: '村长不可爱|zhangjian225'
    bilibili: '村长不可爱|49829377'
    ks: '村长不可爱|paprika225'
    xg: '村长不可爱'
  esdeVersion: '3.4.1'
  raVersion: '1.22.2'
  baiduPan: 'https://pan.baidu.com/s/1FsRW8323Ga_XI142mA-0xQ?pwd=4fva'
  qqGroup: '1021421949'
  feedbackEmail: '809730879@qq.com'
  globalRomWhitelist:
    - 'All Night Nippon Super Mario Bros. (Japan) (Promo).fds'
    - 'Soccer (Japan).fds'
    - 'Super Mario Bros. (Japan).fds'
  globalTagBlacklist:
    - '3DS Virtual Console'
    - '8-bit Adventure Anthology - Volume I'
    - 'Animal Crossing'
    - 'ArchiMENdes Hen'
    - 'Broke Studio'
    - 'Capcom Classics Mini Mix'
    - 'Capcom Town'
    - 'Castlevania Anniversary Collection'
    - 'Competition Cart'
    - 'Contra Anniversary Collection'
    - 'Datach'
    - 'Disney Classic Games'
    - 'e-Reader'
    - 'FamicomBox'
    - 'Konami Collector''s Series'
    - 'Limited Run Games'
    - 'Mega Man Legacy Collection'
    - 'Metal Gear Solid Collection'
    - 'Namco Anthology 1'
    - 'Namco Museum Archives Vol 1'
    - 'Namco Museum Archives Vol 2'
    - 'Namcot Collection'
    - 'Namcot Collection, Namco Museum Archives Vol 1'
    - 'Namcot Collection, Namco Museum Archives Vol 2'
    - 'Ninja JaJaMaru Retro Collection'
    - 'Not For Resale'
    - 'Piko Interactive'
    - 'QUByte Classics'
    - 'Red Art Games'
    - 'Retro Collection'
    - 'Retro-Bit'
    - 'Retro-Bit Generations'
    - 'SNK 40th Anniversary Collection'
    - 'Steam'
    - 'Switch Online'
    - 'Test Program'
    - 'The Cowabunga Collection'
    - 'The Disney Afternoon Collection'
    - 'USA Wii Virtual Console, Wii U Virtual Console'
    - 'Virtual Console'
    - 'Virtual Console, Switch Online'
    - 'Wii and Wii U Virtual Console'
    - 'Wii U Virtual Console'
    - 'Wii Virtual Console'
    - 'GameCube, Virtual Console'
    - 'Collector''s Edition'
    - 'GameCube'
    - "GameCube, Wii and Wii U Virtual Console"
