globalConfig:
  enableBase: false
  enablePlatform: true
  esdeHome: 'D:\ES-DE'
  raHome: 'D:\ES-DE\Emulators\RetroArch-Win64'
  resHome: 'D:\resources'
  repo: 'https://github.com/deathbit/retroboy'
  author:
    name: '村长不可爱'
    wechat: '村长|paprika225'
    qq: '村长不可爱|809730879'
    tiktok: '村长不可爱|paprika0225'
    xhs: '村长不可爱|zhangjian225'
    bilibili: '村长不可爱|49829377'
    ks: '村长不可爱|paprika225'
    xg: '村长不可爱'
  esdeVersion: '3.4.1'
  raVersion: '1.22.2'
  baiduPan: 'https://pan.baidu.com/s/1FsRW8323Ga_XI142mA-0xQ?pwd=4fva'
  qqGroup: '1021421949'
  feedbackEmail: '809730879@qq.com'
