spring:
  application:
    name: retroboy

app:
  config:
    globalConfig:
      raConfig: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
      downloadedMediaDirBase: 'D:\ES-DE\ES-DE\downloaded_media'
      romsAllDir: 'D:\ES-DE\ROMs_ALL'
      romsDir: 'D:\ES-DE\ROMs'
      startupTaskMask: '!CLEAN_UP|!DEFAULT_CONFIG|!FIX_CHINESE_FONT|!SET_MEGA_BEZEL_SHADER|SET_PLATFORM'
      platformTaskMask: '!NES|FDS'
      globalRomWhitelist:
        - 'All Night Nippon Super Mario Bros. (Japan) (Promo).fds'
        - 'Soccer (Japan).fds'
        - 'Super Mario Bros. (Japan).fds'
      globalTagBlacklist:
        - '3DS Virtual Console'
        - '8-bit Adventure Anthology - Volume I'
        - 'Animal Crossing'
        - 'ArchiMENdes Hen'
        - 'Broke Studio'
        - 'Capcom Classics Mini Mix'
        - 'Capcom Town'
        - 'Castlevania Anniversary Collection'
        - 'Competition Cart'
        - 'Contra Anniversary Collection'
        - 'Datach'
        - 'Disney Classic Games'
        - 'e-Reader'
        - 'FamicomBox'
        - 'Konami Collector''s Series'
        - 'Limited Run Games'
        - 'Mega Man Legacy Collection'
        - 'Metal Gear Solid Collection'
        - 'Namco Anthology 1'
        - 'Namco Museum Archives Vol 1'
        - 'Namco Museum Archives Vol 2'
        - 'Namcot Collection'
        - 'Namcot Collection, Namco Museum Archives Vol 1'
        - 'Namcot Collection, Namco Museum Archives Vol 2'
        - 'Ninja JaJaMaru Retro Collection'
        - 'Not For Resale'
        - 'Piko Interactive'
        - 'QUByte Classics'
        - 'Red Art Games'
        - 'Retro Collection'
        - 'Retro-Bit'
        - 'Retro-Bit Generations'
        - 'SNK 40th Anniversary Collection'
        - 'Steam'
        - 'Switch Online'
        - 'Test Program'
        - 'The Cowabunga Collection'
        - 'The Disney Afternoon Collection'
        - 'USA Wii Virtual Console, Wii U Virtual Console'
        - 'Virtual Console'
        - 'Virtual Console, Switch Online'
        - 'Wii and Wii U Virtual Console'
        - 'Wii U Virtual Console'
        - 'Wii Virtual Console'
        - 'GameCube, Virtual Console'
        - 'Collector''s Edition'
        - 'GameCube'
        - "GameCube, Wii and Wii U Virtual Console"
    cleanUpTask:
      cleanDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - 'D:\ES-DE\ROMs'
        - 'D:\ES-DE\ES-DE\themes'
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
    defaultConfigTask:
      copyDirContentsInputs:
        - srcDir: 'D:\ES-DE\ROMs_ALL'
          destDir: 'D:\ES-DE\ROMs'
        - srcDir: 'D:\Resources\RetroArch-Win64\assets'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - srcDir: 'D:\Resources\RetroArch-Win64\autoconfig'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - srcDir: 'D:\Resources\RetroArch-Win64\cheats'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - srcDir: 'D:\Resources\RetroArch-Win64\cores'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - srcDir: 'D:\Resources\RetroArch-Win64\database'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - srcDir: 'D:\Resources\RetroArch-Win64\info'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - srcDir: 'D:\Resources\RetroArch-Win64\overlays'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - srcDir: 'D:\Resources\RetroArch-Win64\shaders'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - srcDir: 'D:\Resources\RetroArch-Win64\system'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - srcDir: 'D:\Resources\themes'
          destDir: 'D:\ES-DE\ES-DE\themes'
      copyFileInputs:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
      raConfigInputs:
        - key: 'input_player1_analog_dpad_mode'
          value: '1'
        - key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - key: 'video_fullscreen'
          value: 'true'
    fixChineseFontTask:
      deleteOriginalFontFile: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg\chinese-fallback-font.ttf'
      copyNewFontFile:
        srcFile: 'D:\Resources\chinese-fallback-font.ttf'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg'
      setNotificationFont:
        key: 'video_font_path'
        value: ':\assets\pkg\chinese-fallback-font.ttf'
    setMegaBezelShaderTask:
      copyMegaBezelPacks:
        srcDir: 'D:\Resources\Mega_Bezel_Packs'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      copyDefaultMegaBezelShader:
        - srcFile: 'D:\Resources\global.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\config'
        - srcFile: 'D:\Resources\retroarch.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      setMegaBezelShaderConfigInputs:
        - key: 'aspect_ratio_index'
          value: '24'
        - key: 'video_allow_rotate'
          value: 'false'
        - key: 'video_driver'
          value: 'vulkan'
        - key: 'video_rotation'
          value: '0'
        - key: 'video_scale_integer'
          value: 'false'
        - key: 'video_shader_enable'
          value: 'true'
    ruleConfigMap:
      NES:
        platform: 'NES'
        ready: true
        romDirName: 'nes'
        defaultCore: 'Mesen'
        datFile: 'D:\Resources\dats\Nintendo - Nintendo Entertainment System.dat'
        romDir: 'D:\Resources\roms\nes'
        targetDirBase: 'D:\ES-DE\ROMs\nes'
        targetAreaConfigs:
          - area: 'EUR'
            fileNameBlackList:
                - 'F-15 Strike Eagle (Europe) (En,Sv,Da,Fi).nes'
                - 'Punch-Out!! (Europe).nes'
                - 'Super Mario Bros. + Duck Hunt (Europe, Asia) (En).nes'
                - 'Super Mario Bros. + Tetris + Nintendo World Cup (Europe) (Rev 1).nes'
                - 'Mario Bros. (Europe) (PAL-MA-0).nes'
                - 'Super Mario Bros. (Europe).nes'
            renameOptions:
              - oldName: 'Mario Bros. (Europe) (PAL-MA-0).nes'
                newName: 'Mario Bros..nes'
              - oldName: 'Mario Bros. (Europe) (PAL-MC-0, Classic Series).nes'
                newName: 'Mario Bros. Classic Series.nes'
          - area: 'JPN'
            fileNameBlackList:
              - 'Kung Fu (Japan, USA) (En).nes'
            renameOptions:
              - oldName: 'Star Wars (Japan) (Namco).nes'
                newName: 'Star Wars (Namco).nes'
              - oldName: 'Star Wars (Japan) (Victor).nes'
                newName: 'Star Wars (Victor).nes'
          - area: 'USA'
        tagBlackList:
          - 'Columbus Circle'
          - 'Digital'
          - 'Evercade'
          - 'iam8bit'
          - 'Menu Cart'
          - 'Pixel Heart'
        fileNameBlackList:
          - 'Donkey Kong (Japan) (En).nes'
          - 'Donkey Kong Classics (USA, Europe).nes'
          - 'Donkey Kong Jr. (Japan) (En).nes'
          - 'Donkey Kong Jr. + Jr. Lesson (Japan) (En).nes'
          - 'Exploding Fist (USA).nes'
          - 'Family BASIC (Japan).nes'
          - 'Family BASIC v2.0 (Japan).nes'
          - 'Family BASIC v2.1 (Japan).nes'
          - 'Family BASIC V3 (Japan).nes'
          - 'Family School (Japan).nes'
          - 'Felix the Cat (World) (En).nes'
          - 'Felix the Cat (World) (Ja).nes'
          - 'Final Fantasy I, II (Japan).nes'
          - 'Firework Thrower Kantaro''s 53 Stations of the Toukaido (World).nes'
          - 'Hyper Olympic (Japan) (En) (Genteiban!).nes'
          - 'Idemitsu - Space College - Kikenbutsu no Yasashii Butsuri to Kagaku (Japan).nes'
          - 'Kidou Senshi Z Gundam - Hot Scramble (Japan) (Final Version).nes'
          - 'NHK Gakuen - Space School - Sansu 5 Nen (Jou) (Japan).nes'
          - 'NHK Gakuen - Space School - Sansu 6 Nen (Ge) (Japan).nes'
          - 'NHK Gakuen - Space School - Sansu 6 Nen (Jou) (Japan).nes'
          - 'Pac-Man (USA) (Tengen).nes'
          - 'Playbox BASIC (Japan).nes'
          - 'Popeye (Japan).nes'
          - 'Punch-Out!! (Japan) (En) (Shouhin Golf Tournament US Course).nes'
          - 'Punch-Out!! (USA).nes'
          - 'Radac Tailor-Made (Japan).nes'
          - 'Raid on Bungeling Bay (Japan).nes'
          - 'Sesame Street - ABC & 123 (USA).nes'
          - 'Stadium Events (USA).nes'
          - 'Super Mario Bros. + Duck Hunt (USA).nes'
          - 'Super Mario Bros. + Duck Hunt + World Class Track Meet (USA) (Rev 1).nes'
          - 'Super Spike V''Ball + Nintendo World Cup (USA).nes'
          - 'Tecmo NBA Basketball (USA) (NES-N7).nes'
          - 'Wild Gunman (Japan, USA) (En).nes'
          - 'Yie Ar Kung-Fu (Japan) (En) (Rev 1.2).nes'
      FDS:
        platform: 'FDS'
        ready: false
        romDirName: 'fds'
        defaultCore: 'Mesen'
        datFile: 'D:\Resources\dats\Nintendo - Family Computer Disk System.dat'
        romDir: 'D:\Resources\roms\fds'
        targetDirBase: 'D:\ES-DE\ROMs\fds'
        targetAreaConfigs:
          - area: 'JPN'
        tagBlackList: []
        fileNameBlackList:
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 1 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 2 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 3 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 4 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 5 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'D167B23' no. 6 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'E180L05' no. 1 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'E180L05' no. 2 and no. 3 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'E180L05' no. 4 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'F087D22' (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'F266F13' (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'G188D21N' no. 1 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'G188D21N' no. 2 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'G188D21N' no. 3 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'J226I22' no. 1 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'J226I22' no. 3 (Japan).fds"
          - "Sunsoft Dev Disk Lot - 'K057G06' (Japan).fds"
          - "Akumajou Dracula (Japan) (Rev 1).fds"
          - "Dirty Pair - Project Eden (Japan).fds"
          - "Esper Dream (Japan).fds"
          - "Famicom Grand Prix - F1 Race (Japan).fds"
          - "Famicom Grand Prix II - 3D Hot Rally (Japan) (DV 5) (Famicom 3D System).fds"
          - "Famicom Grand Prix II - 3D Hot Rally (Japan) (DV 7) (Famicom 3D System).fds"
          - "Famicom Mukashibanashi - Shin Onigashima - Zenpen (Japan) (DV 1).fds"
          - "Golf - US Course (Japan) (DV 1).fds"
          - "Golf - US Course (Japan).fds"
          - "Idol Hotline - Nakayama Miho no Tokimeki High School (Japan) (DV 4).fds"
          - "Idol Hotline - Nakayama Miho no Tokimeki High School (Japan) (DV 6).fds"
          - "Idol Hotline - Nakayama Miho no Tokimeki High School (Japan) (DV 10).fds"
          - "Idol Hotline - Nakayama Miho no Tokimeki High School (Japan) (DV 11) (Disk Writer).fds"
          - "Kiki Kaikai - Dotou Hen (Japan).fds"
          - "Kinnikuman - Kinnikusei Oui Soudatsusen (Japan).fds"
          - "Knight Move (Japan).fds"
          - "Othello (Japan) (DV 2).fds"
          - "SD Gundam World - Gachapon Senshi - Scramble Wars (Japan) (Disk Writer).fds"
          - "Super Mario Bros. 2 (Japan) (En).fds"
          - "Super Mario Bros. 2 (Japan) (En) (Game & Watch - Super Mario Bros.).fds"
          - "Tantei Jinguuji Saburou - Shinjuku Chuuou Kouen Satsujin Jiken (Japan).fds"
          - "Topple Zip (Japan) (Project EGG).fds"
          - "Ultraman - Kaijuu Teikoku no Gyakushuu (Japan) (Disk Writer).fds"
          - "Yume Koujou - Doki Doki Panic (Japan) (DV 1).fds"
          - "Yuushi no Monshou - Deep Dungeon (Japan).fds"
          - "Dot E Creator Contest (Japan).fds"
          - "FMC Disk Card Checker Ver 1.3 (Japan) (Rev 2) (Developer Card).fds"
          - "Golf - Special Course (Japan) (Prize Card).fds"
          - "Golf - Japan Course (Japan).fds"
          - "Golf - Japan Course (Japan) (Prize Card).fds"
          - "Tanigawa Kouji no Shougi Shinan II - Meijin e no Michi - Shinban Tsumeshougi - Tsugi no Itte (Japan) (Disk Writer).fds"
