spring:
  application:
    name: retroboy

app:
  config:
    globalConfig:
      raConfig: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
      downloadedMediaDirBase: 'D:\ES-DE\ES-DE\downloaded_media'
      startupTaskMask: '!CLEAN_UP|!DEFAULT_CONFIG|!FIX_CHINESE_FONT|!SET_MEGA_BEZEL_SHADER|SET_PLATFORM'
      platformTaskMask: 'NES|!SNES|!MD'
      globalTagBlacklist:
        - '3DS Virtual Console'
        - '8-bit Adventure Anthology - Volume I'
        - 'Animal Crossing'
        - 'ArchiMENdes Hen'
        - 'Broke Studio'
        - 'Capcom Classics Mini Mix'
        - 'Capcom Town'
        - 'Castlevania Anniversary Collection'
        - 'Competition Cart'
        - 'Contra Anniversary Collection'
        - 'Datach'
        - 'Disney Classic Games'
        - 'e-Reader'
        - 'FamicomBox'
        - 'Konami Collector''s Series'
        - 'Limited Run Games'
        - 'Mega Man Legacy Collection'
        - 'Metal Gear Solid Collection'
        - 'Namco Anthology 1'
        - 'Namco Museum Archives Vol 1'
        - 'Namco Museum Archives Vol 2'
        - 'Namcot Collection'
        - 'Namcot Collection, Namco Museum Archives Vol 1'
        - 'Namcot Collection, Namco Museum Archives Vol 2'
        - 'Ninja JaJaMaru Retro Collection'
        - 'Not For Resale'
        - 'Piko Interactive'
        - 'QUByte Classics'
        - 'Red Art Games'
        - 'Retro Collection'
        - 'Retro-Bit'
        - 'Retro-Bit Generations'
        - 'SNK 40th Anniversary Collection'
        - 'Steam'
        - 'Switch Online'
        - 'Test Program'
        - 'The Cowabunga Collection'
        - 'The Disney Afternoon Collection'
        - 'USA Wii Virtual Console, Wii U Virtual Console'
        - 'Virtual Console'
        - 'Virtual Console, Switch Online'
        - 'Wii and Wii U Virtual Console'
        - 'Wii U Virtual Console'
        - 'Wii Virtual Console'
    cleanUpTask:
      cleanDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - 'D:\ES-DE\ROMs'
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
    defaultConfigTask:
      copyDirContentsInputs:
        - srcDir: 'D:\ES-DE\ROMs_ALL'
          destDir: 'D:\ES-DE\ROMs'
        - srcDir: 'D:\Resources\RetroArch-Win64\assets'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - srcDir: 'D:\Resources\RetroArch-Win64\autoconfig'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - srcDir: 'D:\Resources\RetroArch-Win64\cheats'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - srcDir: 'D:\Resources\RetroArch-Win64\cores'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - srcDir: 'D:\Resources\RetroArch-Win64\database'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - srcDir: 'D:\Resources\RetroArch-Win64\info'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - srcDir: 'D:\Resources\RetroArch-Win64\overlays'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - srcDir: 'D:\Resources\RetroArch-Win64\shaders'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - srcDir: 'D:\Resources\RetroArch-Win64\system'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
      copyFileInputs:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
      raConfigInputs:
        - key: 'input_player1_analog_dpad_mode'
          value: '1'
        - key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - key: 'video_fullscreen'
          value: 'true'
    fixChineseFontTask:
      deleteOriginalFontFile: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg\chinese-fallback-font.ttf'
      copyNewFontFile:
        srcFile: 'D:\Resources\chinese-fallback-font.ttf'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg'
      setNotificationFont:
        key: 'video_font_path'
        value: ':\assets\pkg\chinese-fallback-font.ttf'
    setMegaBezelShaderTask:
      copyMegaBezelPacks:
        srcDir: 'D:\Resources\Mega_Bezel_Packs'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      copyDefaultMegaBezelShader:
        - srcFile: 'D:\Resources\global.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\config'
        - srcFile: 'D:\Resources\retroarch.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      setMegaBezelShaderConfigInputs:
        - key: 'aspect_ratio_index'
          value: '24'
        - key: 'video_allow_rotate'
          value: 'false'
        - key: 'video_driver'
          value: 'vulkan'
        - key: 'video_rotation'
          value: '0'
        - key: 'video_scale_integer'
          value: 'false'
        - key: 'video_shader_enable'
          value: 'true'
    ruleConfigMap:
      NES:
        platform: 'NES'
        datFile: 'D:\Resources\dats\Nintendo - Nintendo Entertainment System.dat'
        romDir: 'D:\Resources\roms\nes'
        targetDirBase: 'D:\ES-DE\ROMs\nes'
        targetAreaConfigs:
          - area: 'EUR'
            fileNameBlackList:
                - 'F-15 Strike Eagle (Europe) (En,Sv,Da,Fi).nes'
                - 'Miracle Piano Teaching System, The (Germany).nes'
                - 'Monopoly (Germany).nes'
                - 'Punch-Out!! (Europe).nes'
                - 'Super Mario Bros. + Duck Hunt (Europe, Asia) (En).nes'
                - 'Super Mario Bros. + Tetris + Nintendo World Cup (Europe) (Rev 1).nes'
                - 'Teenage Mutant Ninja Turtles (Australia).nes'
                - 'Teenage Mutant Ninja Turtles II - The Arcade Game (Australia).nes'
            renameOptions:
              - oldName: 'Mario Bros. (Europe) (PAL-MA-0).nes'
                newName: 'Mario Bros..nes'
              - oldName: 'Mario Bros. (Europe) (PAL-MC-0, Classic Series).nes'
                newName: 'Mario Bros. Classic Series.nes'
          - area: 'JPN'
            fileNameBlackList: ['Kung Fu (Japan, USA) (En).nes']
            renameOptions:
              - oldName: 'Star Wars (Japan) (Namco).nes'
                newName: 'Star Wars (Namco).nes'
              - oldName: 'Star Wars (Japan) (Victor).nes'
                newName: 'Star Wars (Victor).nes'
          - area: 'USA'
        tagBlackList:
          - 'Columbus Circle'
          - 'Digital'
          - 'Evercade'
          - 'iam8bit'
          - 'Menu Cart'
          - 'Pixel Heart'
        fileNameBlackList:
          - 'Donkey Kong (Japan) (En).nes'
          - 'Donkey Kong Classics (USA, Europe).nes'
          - 'Donkey Kong Jr. (Japan) (En).nes'
          - 'Donkey Kong Jr. + Jr. Lesson (Japan) (En).nes'
          - 'Exploding Fist (USA).nes'
          - 'Family BASIC (Japan).nes'
          - 'Family BASIC v2.0 (Japan).nes'
          - 'Family BASIC v2.1 (Japan).nes'
          - 'Family BASIC V3 (Japan).nes'
          - 'Family School (Japan).nes'
          - 'Felix the Cat (World) (En).nes'
          - 'Felix the Cat (World) (Ja).nes'
          - 'Final Fantasy I, II (Japan).nes'
          - 'Firework Thrower Kantaro''s 53 Stations of the Toukaido (World).nes'
          - 'Hyper Olympic (Japan) (En) (Genteiban!).nes'
          - 'Idemitsu - Space College - Kikenbutsu no Yasashii Butsuri to Kagaku (Japan).nes'
          - 'Kidou Senshi Z Gundam - Hot Scramble (Japan) (Final Version).nes'
          - 'NHK Gakuen - Space School - Sansu 5 Nen (Jou) (Japan).nes'
          - 'NHK Gakuen - Space School - Sansu 6 Nen (Ge) (Japan).nes'
          - 'NHK Gakuen - Space School - Sansu 6 Nen (Jou) (Japan).nes'
          - 'Pac-Man (USA) (Tengen).nes'
          - 'Playbox BASIC (Japan).nes'
          - 'Popeye (Japan).nes'
          - 'Punch-Out!! (Japan) (En) (Shouhin Golf Tournament US Course).nes'
          - 'Punch-Out!! (USA).nes'
          - 'Radac Tailor-Made (Japan).nes'
          - 'Raid on Bungeling Bay (Japan).nes'
          - 'Sesame Street - ABC & 123 (USA).nes'
          - 'Stadium Events (USA).nes'
          - 'Super Mario Bros. + Duck Hunt (USA).nes'
          - 'Super Mario Bros. + Duck Hunt + World Class Track Meet (USA) (Rev 1).nes'
          - 'Super Spike V''Ball + Nintendo World Cup (USA).nes'
          - 'Tecmo NBA Basketball (USA) (NES-N7).nes'
          - 'Wild Gunman (Japan, USA) (En).nes'
          - 'Yie Ar Kung-Fu (Japan) (En) (Rev 1.2).nes'
