package com.github.deathbit.retroboy.enums;

public enum BasePackTask {
    DELETE_ALL_TASK,
    SET_UP_ESDE_BASE_TASK,
    SET_UP_ESDE_UPDATE_TASK,
    SET_UP_RETROARCH_BASE_TASK,
    SET_UP_RETROARCH_UPDATE_TASK,
    SET_UP_RETROARCH_DEFAULT_CONFIG_TASK,
    SET_UP_RETROARCH_FIX_CHINESE_FONT_TASK,
    SET_UP_RETROARCH_MEGA_BEZEL_SHADER_TASK,
    BASE_PACK_RELEASE_TASK
}
